### ISSUE TITLE
data blob insert and recovery example

### ISSUE THREAD

**Issue by dehann** [GearsAD/GraffSDK.jl#23]
please...

**Comment by GearsAD** [comment]
WIP - https://github.com/GearsAD/SynchronySDK.jl/tree/feature/data_documentation_and_refactor

**Comment by GearsAD** [comment]
Done - [https://gearsad.github.io/GraffSDK.jl/latest/working_with_data.html#An-Overview-of-Our-Data-Model-1](https://gearsad.github.io/GraffSDK.jl/latest/working_with_data.html#An-Overview-of-Our-Data-Model-1)
