### ISSUE TITLE
Why pack json in json FactorBody

### ISSUE THREAD

**Issue by dehann** [GearsAD/GraffSDK.jl#24]
https://github.com/GearsAD/SynchronySDK.jl/blob/521b47b87f511ff3624765e959ce2d55c30fd340/src/entities/Session.jl#L127

- 1.) What is the cost of flexibility?
- 2.) Is a factor spec required?

**Comment by dehann** [comment]
cc @pvazteixeira

**Comment by dehann** [comment]
`fctBody` is parsed into a full actual julia object.

**Comment by dehann** [comment]
Ah, you are using Packed data types as JSON strings -- thanks.

**Comment by GearsAD** [comment]
All good right? More to follow on this discussion, will open separate issue
