### ISSUE TITLE
Best way to create and send factors from GraffSDK? 

### ISSUE THREAD

**Issue by GearsAD** [GearsAD/GraffSDK.jl#35]
Best way to create and send factors from GraffSDK? 

I'd like to make this as simple (simpler?) than the local implementation.

Currently done like this, note the complexity:
```
# Our measurements
deltaMeasurement = [1.0; 1.0; pi/4] #Same as above - a (1,1) move with a 45 degree heading change
pOdo = Float64[0.1 0 0; 0 0.1 0; 0 0 0.01]
# Creating the factor body - We are working on making this cleaner
p2p2 = Pose2Pose2(MvNormal(deltaMeasurement, pOdo.^2))
p2p2Conv = convert(PackedPose2Pose2, p2p2)
p2p2Request = FactorRequest(["x0", "x1"], "Pose2Pose2", p2p2Conv)
```

I have the following concerns/questions:

- How should we simplify this?
- [Dependencies] Currently we have to import RoME+Distributions into GraffSDK. That's a big import, basically bringing solver into SDK as dependency. Do you think we should do that fully (RoME is official dependency of GraffSDK), or we find another way to get the factor contracts into GraffSDK?
- [Schema and Language Agnosticism] We need to consider this for other languages as well - how do we manage factor schema in various languages? It may be worth making a library of factor contracts per language. Or should we use JSONSchema?
- [Extensibility] We also have to consider adding custom factors. Should we look at a factor database? This would have to contain code. What about external factor repos which are brought into Julia programmatically? Factor management comes into the picture quickly.

Ref:
[JSON Schema](https://json-schema.org/)
[Julia JSONSchema](https://github.com/fredo-dedup/JSONSchema.jl)

@dehann @pvazteixeira @nicrip

**Comment by pvazteixeira** [comment]
It would definitely be great to have a language-agnostic specification that we could pull in to other languages - we ran into this with [C++](https://github.com/pvazteixeira/graff_cpp) and [Python](https://github.com/nicrip/SynchronySDK_py). What would be the reasons not to go the [gRPC](https://www.grpc.io) route and define the API (including nodes and factors) inside a `.proto` ([example](https://github.com/grpc/grpc/blob/v1.14.1/examples/protos/route_guide.proto))? At least initially we'd have good language support w.r.t. JSON Schema [implementations](https://json-schema.org/implementations.html).

**Comment by GearsAD** [comment]
Good point - could do protobufs too. Let's discuss a bit after 15th?

**Comment by GearsAD** [comment]
Going with the ZMQ Caesar solution!
