### ISSUE TITLE
UndefVarError: PackedPose2Point2Bearing not defined

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#69]
UndefVarError: PackedPose2Point2Bearing not defined when running 
```juila
p2br = Pose2Point2Bearing(Normal(ψ,0.05))
addFactor([psym; lsym], p2br)
```

**Comment by GearsAD** [comment]
Ah, you need to import Caesar before doing that - GraffSDK doesn't import Caesar by default as it's not needed for all operations.

That help?
