### ISSUE TITLE
Add node to big data entry key

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#79]
Creating big data entries only uses id as key and not the node as well (is user, robot, session used?). For example only one AT1 is made in the database using the following code snippet:
```julia
bde = BigDataElementRequest("AT1", "mongo", "Detections at $nnode", JSON.json(tagdict[:x1]))
    setData(:x1, bde)
bde = BigDataElementRequest("AT1", "mongo", "Detections at $nnode", JSON.json(tagdict[:x2]))
    setData(:x2, bde)
```

**Comment by GearsAD** [comment]
Eek, good one! Fixed and merging now.

**Comment by GearsAD** [comment]
@Affie Merged, it's not labelled yet, want to get few more changes in this weekend, could you pull master? Please let me know if it resolves your issue?

**Comment by Affie** [comment]
Thanks for fixing so quickly!
