### ISSUE TITLE
deleteSession fails

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#81]
HTTP.ExceptionRequest.StatusError(400, HTTP.Messages.Response:
"""
HTTP/1.1 400 Bad Request
Date: Mon, 28 Jan 2019 08:27:28 GMT
Content-Type: application/json
Content-Length: 3376
Connection: keep-alive
x-amzn-RequestId: 8c6a8e77-22d6-11e9-b044-dffcc8df56b8
x-amz-apigw-id: UNJ1lHMDoAMF-Ug=
x-amzn-Remapped-Server: Julia/1.0.2
x-amzn-Remapped-Date: Mon, 28 Jan 2019 08:27:28

UndefVarError: Response not defined
Stacktrace:
 [1] deleteSession() at /home/ubuntu/.julia/dev/SlamInDB_WebAPI/app/resources/sessions/SessionController.jl:89
 [2] #invokelatest#1 at ./essentials.jl:697 [inlined]
 [3] invokelatest at ./essentials.jl:696 [inlined]
 [4] match_routes(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Nothing, ::Genie.Router.Params{Any}) at /home/ubuntu/.julia/dev/Genie/src/Router.jl:458
 [5] route_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/ubuntu/.julia/dev/Genie/src/Router.jl:87
 [6] handle_request(::HTTP.Messages.Request, ::HTTP.Messages.Response, ::Sockets.IPv4) at /home/ubuntu/.julia/dev/Genie/src/AppServer.jl:96
 [7] handle_request at /home/ubuntu/.julia/dev/Genie/src/AppServer.jl:95 [inlined]
 [8] #12 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Distributed/src/macros.jl:108 [inlined]
 [9] run_work_thunk(::getfield(Genie.AppServer, Symbol("##12#15")){HTTP.Messages.Request,HTTP.Me
⋮
3376-byte body
""")
#request#1 at ExceptionRequest.jl:22 [inlined]
(::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction, :aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Nothing,Bool,String,String,String,String}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Array{UInt8,1}) at none:0
(::getfield(Base, Symbol("###44#45#46")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,Any,NTuple{6,Symbol},NamedTuple{(:iofunction, :aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Nothing,Bool,String,String,String,String}}}, ::Function, ::Type, ::Vararg{Any,N} where N) at error.jl:203
##44#47 at none:0 [inlined]
#request#1 at RetryRequest.jl:44 [inlined]
(::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction, :aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Nothing,Bool,String,String,String,String}}, ::typeof(HTTP.request), ::Type{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Array{UInt8,1}) at none:0
#request#1(::Base.Iterators.Pairs{Symbol,Any,NTuple{6,Symbol},NamedTuple{(:iofunction, :aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Nothing,Bool,String,String,String,String}}}, ::Function, ::Type{HTTP.AWS4AuthRequest.AWS4AuthLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Array{UInt8,1}) at AWS4AuthRequest.jl:34
#request at none:0 [inlined]
#request#1(::VersionNumber, ::String, ::Nothing, ::Nothing, ::Base.Iterators.Pairs{Symbol,Any,NTuple{5,Symbol},NamedTuple{(:aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Bool,String,String,String,String}}}, ::Function, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.AWS4AuthRequest.AWS4AuthLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}) at MessageRequest.jl:47
(::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Bool,String,String,String,String}}, ::typeof(HTTP.request), ::Type{HTTP.MessageRequest.MessageLayer{HTTP.AWS4AuthRequest.AWS4AuthLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}) at none:0
#request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Symbol,Any,NTuple{5,Symbol},NamedTuple{(:aws_authorization, :aws_service, :aws_region, :aws_access_key_id, :aws_secret_access_key),Tuple{Bool,String,String,String,String}}}, ::Function, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.AWS4AuthRequest.AWS4AuthLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoo...

**Comment by GearsAD** [comment]
Fixed in API! Merging now
