### ISSUE TITLE
Undefined symbol: mbedtls_x509_crt_verify_restartable with MbedTLS v0.6.7

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#84]
FIY, https://github.com/JuliaWeb/MbedTLS.jl/issues/193
Pining to v0.6.6 solves this for now

**Comment by GearsAD** [comment]
Looks resolved, ok if I close this?

**Comment by Affie** [comment]
I just put it here in case anybody else struggles with error in V0.6.7.
