### ISSUE TITLE
Should duplicate addVariable still work

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#86]
It looks like if a duplicate (landmark in this case) is made with addVariable it gives an error but the landmark is not added to the factor graph. 
Should we not just give a warning/error and still add the landmark assuming there is just one? Related to https://github.com/JuliaRobotics/IncrementalInference.jl/issues/188

**Comment by GearsAD** [comment]
According to discussion it also deletes it, need to fix - thanks!

**Comment by GearsAD** [comment]
I ran a number of tests to try get it to delete a variable, and was unable to reproduce that.

Given multiple creation requests for x0 and l0, I see dead messages in the queue:
```
4-element Array{Any,1}:
 Dict{String,Any}("userId"=>"NewUser","nodeId"=>"","sessionId"=>"HexMultisession5db30e","robotId"=>"DemoRobot","error"=>"Cannot create a symbolic node for label 'l0', expected no nodes received 1 nodes...","bigDataKey"=>"","payload"=>"{\"label\":\"l0\",\"variableType\":\"Point2\",\"N\":100,\"labels\":[\"LANDMARK\"]}","request"=>"postVariable")
 Dict{String,Any}("userId"=>"NewUser","nodeId"=>"","sessionId"=>"HexMultisession5db30e","robotId"=>"DemoRobot","error"=>"Cannot create a symbolic node for label 'l0', expected no nodes received 1 nodes...","bigDataKey"=>"","payload"=>"{\"label\":\"l0\",\"variableType\":\"Point2\",\"N\":100,\"labels\":[\"LANDMARK\"]}","request"=>"postVariable")
 Dict{String,Any}("userId"=>"NewUser","nodeId"=>"","sessionId"=>"HexMultisession5db30e","robotId"=>"DemoRobot","error"=>"Cannot create a symbolic node for label 'l0', expected no nodes received 1 nodes...","bigDataKey"=>"","payload"=>"{\"label\":\"l0\",\"variableType\":\"Point2\",\"N\":100,\"labels\":[\"LANDMARK\"]}","request"=>"postVariable")
 Dict{String,Any}("userId"=>"NewUser","nodeId"=>"","sessionId"=>"HexMultisession5db30e","robotId"=>"DemoRobot","error"=>"Cannot create a symbolic node for label 'x0', expected no nodes received 1 nodes...","bigDataKey"=>"","payload"=>"{\"label\":\"x0\",\"variableType\":\"Point2\",\"N\":100,\"labels\":[\"POSE\"]}","request"=>"postVariable")
```

In none of my cases was the node ever deleted though. Curious, @Affie, did you do anything else that may have triggered a deletion?

**Comment by Affie** [comment]
I wasn't able to reproduce the deletion, so I think it wasn't actually deleted but mislabeled as a POSE. If I use GraffSDK.ls() it returns it and seems to work as expected. Although its labeled as a POSE and LANDMARK, but thats another issue.
