### ISSUE TITLE
Node not found when calling setData with node label

### ISSUE THREAD

**Issue by Affie** [GearsAD/GraffSDK.jl#97]
{"message":"Graff.Model.Variable with id '0', node label 'x13', and labels 'VARIABLE:[userId]:[robotId]:[sessionId' not found","traceId":"b078c91"}""")

**Comment by GearsAD** [comment]
Current behavior is synchronous upload, so if you've added variables and factors to the queue, you'll need to wait for them to be processed before assigning data to them.

I've uploaded the hexagonal example demonstrating this, and I use the label to upload the data to make sure it works using label. Would suggest using this pattern at the moment: https://github.com/GearsAD/GraffSDK.jl/blob/master/examples/6_HexagonalSLAM.jl#L79-L110

However I think asynchronous upload is the best way forward, we've got an issue for this - #100. Are you ok with closing this and tracking that as an enhancement?
